# Utilisation de notebooks `Python` pour traiter les données MobPro

- Webinaire [Expertises-territoires][web] - vendredi 5 juin 2026
- Daniel Marin - [OpenDC][odc] (dmarin@open-dc.com)

[web]: https://www.expertises-territoires.fr/jcms/pl1_976691/fr/5/6/25-webinaire-utilisation-des-donnees-de-mobpro-de-l-insee
[odc]: https://www.open-dc.com/fr/

## Sommaire

* [Présentation des `Notebook Jupyter` pour `Python`](#présentation-des-notebook-jupyter-pour-python)
* [Où trouver la donnée MobPro / MobSco](#où-trouver-la-donnée-mobpro--mobsco)
* [Préparation de la donnée](#préparation-de-la-donnée)
* [Exports](#exports)

## Présentation des `Notebook Jupyter` pour `Python`

### Motivation

* Les données `MobPro` sont trop volumineuses pour être traitées sous `Excel` (~8M de lignes, pour un maximum théorique de 1 048 576 de lignes pour les fichiers `Excel`)
* La programmation en `Python` permet:
    * un chainage des traitements,
    * rapidité et efficacité dans l'écriture et l'exécution du code,
    * un croisement aisé avec des sources de données externes (emplois, population, données géographiques etc.),
    * une transparence et reproductibilité des traitements effectués.

### Comment utiliser `Python`

Pour plus de détails, se reporter au précédent webinaire sur la [Mise en oeuvre de Notebooks Python pour traiter des données de mobilités](https://colab.research.google.com/github/daniel-odc/Webinaire_CEREMA_OpenDC/blob/main/Notebooks_for_moblity.ipynb).

#### Environnements de travail communs

| Solution                                                                                                                                                                                        | Avantages                                                                                                             | Inconvénients                                                                                                                                        | Public visé                                                          |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------|
| [`Jupyterlite`][lite] <br> ![lite](./img/logo_jupyterlite.png)                                                                                                                                  | Gratuit <br> Pas de création de compte <br> Fonctionne hors ligne                                                     | Peu de librairies compatibles                                                                                                                        | Débutant pour un apprentissage des bases de `Python`                 |
| [`Google Colab`][colab] <br> ![colab](./img/logo_colab.png)                                                                                                                                     | Gratuit <br> Grand nombre de librairies compatibles <br> Fonction de partage de notebooks et d'édition à plusieurs    | Nécessité de se connecter avec son compte Google <br> A éviter pour le traitement de données confidentielles <br> Fonctionnement en ligne uniquement | Équipe pour de petits projets, ouverts et collaboratifs              |
| [`SSP Cloud`][onyxia] <br> ![onyxia](./img/logo_onyxia.png)                                                                                                                                     | Gratuit <br> Mise à disposition de ressources CPU et RAM importantes                                                  | Accessible uniquement aux agents de la fonction publique <br> Fonctionnement en ligne uniquement                                                     | Équipe de la fonction publique ayant besoin de resources importantes |
| IDE <br> [Pycharm][pycharm] ![pycharm](./img/logo_pycharm.png) <br> [VS Code][vscode] ![vscode](./img/logo_vscode.png) <br> [Positron][positron] ![positron](./img/logo_positron.png) <br><br> etc. | Adapté à toutes tailles de projet <br> Fonctionnement hors ligne <br> Liberté sur les choix de librairies à installer | Certaines solutions sont payantes                                                                                                                    | Équipes ou développeurs travaillant sur des projets amenés à grossir |

💡Pour le partage de projet et le développement collaboratif, se tourner vers [`Git`](https://git-scm.com/) qui s'interface avec toutes les solutions ci-dessus.


[lite]: https://jupyterlite.github.io/demo/lab/index.html
[colab]: https://colab.research.google.com/
[onyxia]: https://datalab.sspcloud.fr/
[pycharm]: https://www.jetbrains.com/pycharm/
[vscode]: https://code.visualstudio.com/
[positron]: https://posit.co/

## Où trouver la donnée MobPro / MobSco

### Téléchargement direct

Sur le [site de l'INSEE](https://www.insee.fr/fr/statistiques/8582949):
* [Données MobPro 2022](https://www.insee.fr/fr/statistiques/fichier/8582949/base-flux-mobilite-domicile-lieu-travail-2022_csv.zip)
* [Données MobSco 2022](https://www.insee.fr/fr/statistiques/fichier/8582969/base-flux-mobilite-domicile-lieu-etude-2022_csv.zip)

### Avec l'API `Pynsee`

## Présentation de l'API Pynsee

Package python fournissant des outils pour faciliter la recherche et la collecte des données provenant de l’INSEE et de l’IGN.

[Documentation](https://pynsee.readthedocs.io/en/latest/index.html)

### Intérêt

* Permet d'inclure dans la chaine de traitement la partie téléchargement
* Assure une meilleure reproductibilité du traitement
* Facilite les mises à jour lors de la création de nouvelles bases.

### Accès

* Récupération d'une **clé API** sur le site
* [Présentation et tutoriel d'Hadrien Leclerc](https://minio.lab.sspcloud.fr/ssphub/diffusion/website/2023-02-opendata_Insee/pynsee_slides.pdf)

![Chargement depuis un fichier local](./img/cell1_chargement_local.png)

In [1]:
# Préparation de la donnée
import pandas as pd  # Lancer avant `pip install pandas`

# # Chargement des bases:

# # # Option 1: Chargement depuis un fichier local téléchargé depuis le site de l'INSEE:
# ~1min30 de chargement en mémoire (hors temps de téléchargement manuel)

# # (adaptez votre répertoire local où vous avez sauvegardé les fichiers)
df_mobpro = pd.read_csv(r'c:\Users\dmarin\Downloads\FD_MOBPRO_2018.zip', sep=';', low_memory=False)
df_mobsco = pd.read_csv(r'c:\Users\dmarin\Downloads\FD_MOBSCO_2018.zip', sep=';', low_memory=False)

print(f'df_mobpro: {len(df_mobpro.index):,} enregistrements\n')  # 7,932,895 enregistrements
display(df_mobpro.head())

print(f'df_mobsco: {len(df_mobsco.index):,} enregistrements\n')  # 4,747,781 enregistrements
display(df_mobsco.head())

df_mobpro: 7,932,895 enregistrements

,COMMUNE,ARM,DCFLT,DCLT,AGEREVQ,CS1,DEROU,DIPL,EMPL,ILT,...,REGION,REGLT,SEXE,STAT,STOCD,TP,TRANS,TYPL,TYPMR,VOIT
0,01001,ZZZZZ,99999,01001,20,6,Z,16,16,1,...,84,84,1,10,10,2,1,1,41,1
1,01001,ZZZZZ,99999,01001,60,1,Z,13,21,1,...,84,84,1,21,10,1,1,1,11,1
2,01001,ZZZZZ,99999,01001,50,4,Z,14,16,1,...,84,84,2,10,10,2,1,1,41,1
3,01001,ZZZZZ,99999,01001,50,2,Z,13,22,1,...,84,84,1,22,10,1,1,1,41,1
4,01001,ZZZZZ,99999,01001,55,4,Z,13,16,1,...,84,84,2,10,10,2,5,1,12,1

df_mobsco: 4,747,781 enregistrements

,COMMUNE,ARM,DCETUE,DCETUF,AGEREV10,CSM,DEROU,DIPL,ILETUD,ILETUU,...,IPONDI,LPRM,METRODOM,NPERR,REGION,REGETUD,SEXE,STOCD,TYPMR,VOIT
0,01001,ZZZZZ,99999,01001,6,5,Z,ZZ,1,1,...,4.774761,3,M,6,84,84,2,10,43,2
1,01001,ZZZZZ,99999,01001,11,5,Z,ZZ,1,1,...,4.774761,3,M,6,84,84,1,10,43,2
2,01001,ZZZZZ,99999,01001,6,4,Z,ZZ,1,1,...,4.860337,3,M,5,84,84,2,10,41,2
3,01001,ZZZZZ,99999,01001,6,6,Z,ZZ,1,1,...,5.036118,3,M,3,84,84,1,10,32,1
4,01001,ZZZZZ,99999,01001,6,4,Z,ZZ,1,1,...,4.947447,3,M,4,84,84,2,10,41,2

![Chargement via l'API Pynsee](./img/cell2_chargement_api.png)

In [1]:
# # # Option 2: Chargement depuis l'API Pynsee: ~3min: téléchargement + chargement en mémoire
import pynsee # Lancer avant `pip install pynsee`

df_mobpro = pynsee.download.download_file('RP_MOBPRO_2018')
df_mobsco = pynsee.download.download_file('RP_MOBSCO_2018')

print(f'df_mobpro: {len(df_mobpro.index):,} enregistrements\n')  # 7,932,895 enregistrements
print(f'df_mobsco: {len(df_mobsco.index):,} enregistrements\n')  # 4,747,781 enregistrements

C:\Users\dmarin\AppData\Roaming\Python\Python314\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Downloading: 100%|██████████| 87.4M/87.4M [01:13<00:00, 1.25MiB/s]
Extracting: 100%|██████████| 808M/808M [00:01<00:00, 562MB/s]
Downloading: 100%|██████████| 34.4M/34.4M [00:30<00:00, 1.17MiB/s]
Extracting: 100%|██████████| 373M/373M [00:00<00:00, 535MB/s]

df_mobpro: 7,932,895 enregistrements

df_mobsco: 4,747,781 enregistrements

![Sélection des colonnes et dictionnaires de valeurs](./img/cell3_selection_colonnes.jpg)

In [9]:
# # Extraction des champs pertinents et réagencement des bases:

# Sélection des colonnes qui nous intéressent:
col_pro = ['COMMUNE', 'ARM', 'DCLT', 'IPONDI', 'TP', 'TRANS']   # mobpro
col_sco = ['COMMUNE', 'ARM', 'DCETUF', 'IPONDI']                # mobsco

# Renommage des colonnes de façon plus explicite:
dict_rename = {
    'COMMUNE':  'depuis',           # commune d'origine dans les fichiers mobpro et mobsco (hors Paris, Lyon, Marseille)
    'ARM':      'arrondissement',   # arrondissement d'origine pour Paris, Lyon, Marseille dans les fichiers mobpro et mobsco
    'DCLT':     'vers',             # commune de destination dans les fichiers mobpro
    'DCETUF':   'vers',             # commune de destination dans les fichiers mobsco
    'IPONDI':   'poids',            # pondération de l'individu dans les fichiers mobpro et mobsco
    'TP':       'temps_partiel',    # indication de temps partiel / temps plein dans les fichiers mobpro
    'TRANS':    'mode'              # mode de transport pour aller travailler dans les fichiers mobpro
}

# Dictionnaires de valeurs de champs:

# Modes de transport:
dict_mode = {
    1: 'pas_de_transport',
    2: 'marche',          # Marche à pied(ou rollers, patinette)
    3: 'vélo',            # Vélo(y compris à assistance électrique) (apparu depuis les bases 2018)
    4: '2rm',             # Deux - roues motorisé
    5: 'vp',              # Voiture, camion, fourgonnette
    6: 'tc',              # Transports en commun
    'Z': 'nan'}             # non resnsigné

#   Temps partiel vs temps plein:
dict_tp = {
    1: 1,     # 'Temps complet'
    2: 0.5}   # 'Temps partiel: on suppose un mi-temps

In [10]:
# # Sélection et renommage des colonnes pertinentes:

# Sélection des colonnes:
df_pro = df_mobpro[col_pro].rename(columns=dict_rename)
df_sco = df_mobsco[col_sco].rename(columns=dict_rename)

# Remplacement des valeurs par des valeurs plus explicites:
df_pro['mode'] = df_pro['mode'].replace(dict_mode)
df_pro['temps_partiel'] = df_pro['temps_partiel'].replace(dict_tp)

print(f'df_pro:')
display(df_pro.head())

print(f'df_sco:')
display(df_sco.head())

df_pro:

  depuis arrondissement   vers     poids  temps_partiel              mode
0  01001          ZZZZZ  01001  5.036118            0.5  pas_de_transport
1  01001          ZZZZZ  01001  5.218256            1.0  pas_de_transport
2  01001          ZZZZZ  01001  5.036118            0.5  pas_de_transport
3  01001          ZZZZZ  01001  5.036118            1.0  pas_de_transport
4  01001          ZZZZZ  01001  5.218256            0.5                vp

df_sco:

  depuis arrondissement   vers     poids
0  01001          ZZZZZ  01001  4.774761
1  01001          ZZZZZ  01001  4.774761
2  01001          ZZZZZ  01001  4.860337
3  01001          ZZZZZ  01001  5.036118
4  01001          ZZZZZ  01001  4.947447

![Gestion des arrondissements et pondération temps partiel](./img/cell5_arrondissements_poids.jpg)

In [11]:
# # Remplacement des communes par les arrondissements pour Paris Lyon, Marseille
df_pro.loc[(df_pro['arrondissement'] != 'ZZZZZ'), 'depuis'] = df_pro.loc[(df_pro['arrondissement'] != 'ZZZZZ'), 'arrondissement']
df_sco.loc[(df_sco['arrondissement'] != 'ZZZZZ'), 'depuis'] = df_sco.loc[(df_sco['arrondissement'] != 'ZZZZZ'), 'arrondissement']


# Pondération du poids par le temps partiel
df_pro['poids'] = df_pro['poids'] * df_pro['temps_partiel']

# Retrait des colonnes arrondissement et temps partiel:
df_pro.drop(columns=['arrondissement', 'temps_partiel'], inplace=True)
df_sco.drop(columns=['arrondissement'], inplace=True)

print(f'df_pro:')
display(df_pro.head())

print(f'df_sco:')
display(df_sco.head())

df_pro:

  depuis   vers     poids              mode
0  01001  01001  2.518059  pas_de_transport
1  01001  01001  5.218256  pas_de_transport
2  01001  01001  2.518059  pas_de_transport
3  01001  01001  5.036118  pas_de_transport
4  01001  01001  2.609128                vp

df_sco:

  depuis   vers     poids
0  01001  01001  4.774761
1  01001  01001  4.774761
2  01001  01001  4.860337
3  01001  01001  5.036118
4  01001  01001  4.947447

![Agrégation groupby et pivot par mode de transport](./img/cell6_groupby_pivot.jpg)

In [22]:
# # Regroupement des enregistrements par 'depuis'-'vers':

# Prise en compte des temps partiels
df_pro = df_pro.groupby(by=['depuis', 'vers', 'mode'], as_index=False)['poids'].sum()
df_sco = df_pro.groupby(by=['depuis', 'vers'], as_index=False)['poids'].sum()

# Pivot par mode de transport: une colonne par mode:
df_pro_pivot = pd.pivot_table(df_pro, index=['depuis', 'vers'], columns='mode', fill_value=0)

# Transforme les noms de colonnes de 'poids marche' à simplement 'marche':
df_pro_pivot.columns = [f"{col[1]}" for col in df_pro_pivot.columns]  # removes MultiIndex

print(f'df_pro:')
display(df_pro_pivot.head())

df_pro:

              2rm  marche  pas_de_transport       tc         vp  vélo
depuis vers
01001  01001  0.0     0.0         25.362728  2.38738  30.405175   0.0
       01053  0.0     0.0          0.000000  0.00000  35.167333   0.0
       01093  0.0     0.0          0.000000  0.00000  47.629361   0.0
       01159  0.0     0.0          0.000000  0.00000   4.947447   0.0
       01165  0.0     0.0          0.000000  0.00000   4.860337   0.0

In [30]:
# ajout total flux pro:
df_pro_pivot['tot_pro'] = 0
for mode in dict_mode.values():
    if mode in df_pro_pivot.columns:
        df_pro_pivot['tot_pro'] = df_pro_pivot['tot_pro'] + df_pro_pivot[mode]

# renomme total flux scolaires:
df_sco.rename(columns={'poids': 'tot_sco'}, inplace=True)

print(f'df_pro:')
display(df_pro_pivot.head())

print(f'df_sco:')
display(df_sco.head())

df_pro:

              2rm  marche  pas_de_transport       tc         vp  vélo  \
depuis vers
01001  01001  0.0     0.0         25.362728  2.38738  30.405175   0.0
       01053  0.0     0.0          0.000000  0.00000  35.167333   0.0
       01093  0.0     0.0          0.000000  0.00000  47.629361   0.0
       01159  0.0     0.0          0.000000  0.00000   4.947447   0.0
       01165  0.0     0.0          0.000000  0.00000   4.860337   0.0

                tot_pro
depuis vers
01001  01001  58.155283
       01053  35.167333
       01093  47.629361
       01159   4.947447
       01165   4.860337

df_sco:

  depuis   vers    tot_sco
0  01001  01001  58.155283
1  01001  01053  35.167333
2  01001  01093  47.629361
3  01001  01159   4.947447
4  01001  01165   4.860337

![Fusion des tables professionnelles et scolaires](./img/cell8_fusion.png)

In [32]:
# # Fusion des tables scolaires et professionnelles:

# Fusion des tables sur les depuis-vers:
df_mob = df_pro_pivot.merge(df_sco, on=['depuis', 'vers'], how='left')

print(f'df_mob: {len(df_mob.index):,} enregistrements')
display(df_mob.head())

df_mob: 942,385 enregistrements

,depuis,vers,2rm,marche,pas_de_transport,tc,vp,vélo,tot_pro,tot_sco
0,01001,01001,0.0,0.0,25.362728,2.38738,30.405175,0.0,58.155283,58.155283
1,01001,01053,0.0,0.0,0.000000,0.00000,35.167333,0.0,35.167333,35.167333
2,01001,01093,0.0,0.0,0.000000,0.00000,47.629361,0.0,47.629361,47.629361
3,01001,01159,0.0,0.0,0.000000,0.00000,4.947447,0.0,4.947447,4.947447
4,01001,01165,0.0,0.0,0.000000,0.00000,4.860337,0.0,4.860337,4.860337

## Exports

Vous pouvez ensuite sélectionner les communes qui vous intéressent, agréger par département, région etc. en dehors de votre zone d'intérêt, puis exporter les tables réduites en `Excel` ou `csv` pour prolonger les analyses éventuellement.

## Pour aller plus loin

* `Python` pour débutants: cours de [Codecademy](https://www.codecademy.com/learn/learn-python-3) (innombrables ressources en ligne)
* `Python` pour la data science et l'analyse géographique: [Cours ENSAE de Lino Galiana](https://pythonds.linogaliana.fr/)
* Tutoriel OpenDC - [Intro à Python et Cookbook GeoPandas pour les données de mobilité](https://colab.research.google.com/github/daniel-odc/td_pythonds_ensae/blob/main/notebooks/cookbook_geopandas_OpenDC.ipynb#scrollTo=wtUQGTaxgw4M)
* Documentation [`Pandas`](https://pandas.pydata.org/docs/user_guide/index.html)